server:
  port: 8082

spring:
  application:
    name:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    database:
    hibernate:
      ddl-auto: none
    show-sql: true # 다솔님 설정
    properties:
      hibernate.format_sql: true
      dialect:
  jwt: # jwt secretkey 남주
    secret:  # 남주님 설정

# swagger 관련 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

tag:
  version: 1.0.0